version: "3.9"

services:
  cassandra-leader:
    image: cassandra:latest
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - 9042:9042
    volumes:
      - ./data/cassandra-leader:/var/lib/cassandra
      - ./etc/cassandra-leader:/etc/cassandra
    env_file:
      - .env

  cassandra-seed-1:
    image: cassandra:latest
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - 9043:9042
    volumes:
      - ./data/cassandra-seed-1:/var/lib/cassandra
      - ./etc/cassandra-seed-1:/etc/cassandra
    env_file:
      - .env
    depends_on:
      cassandra-leader:
        condition: service_started

  cassandra-seed-2:
    image: cassandra:latest
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    ports:
      - 9044:9042
    volumes:
      - ./data/cassandra-seed-2:/var/lib/cassandra
      - ./etc/cassandra-seed-2:/etc/cassandra
    env_file:
      - .env
    depends_on:
      cassandra-seed-1:
        condition: service_started
